---
title: "Final Project"
last updated: 3/5/18
---

## FINAL PROJECT

```{r Setup}
# Libraries
library(readxl)
library(dplyr)
library(moments)
library(stringr)
library(scales)
library(ggplot2)
library(jsonlite)
library(utils)
library(rgdal)
library(readstata13)
library(RColorBrewer)
library(classInt)
library(ggmap)
library(googleway)
library(pander)

# Functions
getMode = function(aColumn){
  freqTable=table(aColumn)
  maxFrequency=max(freqTable)
  names(freqTable[freqTable==maxFrequency])
}
```

```{r Import Data: Initial}
# Import initial survey responses from 2_15_13
temp = tempfile(fileext = '.xlsx') #extension for Excel fie
dataURL <- "https://github.com/lrsulli/Project/raw/master/Data/fp_survey_2_15_13.xlsx" #link to data
download.file(dataURL, destfile = temp, mode = 'wb') #temporarily download file

data_initial = read_excel(temp, sheet = 1) #get data
```

```{r Import Data: Recodes}
# Recode file for Q12 and Q22 to Q25
temp = tempfile(fileext = '.xlsx') #extension for Excel fie
dataURL <- "https://github.com/lrsulli/Project/raw/master/Data/recode_Q12_Q22toQ25.xlsx" #link to data
download.file(dataURL, destfile = temp, mode = 'wb') #temporarily download file

data_recode = read_excel(temp, sheet = 1) #get data
```

```{r Import Data: Addresses}
# Address list data file
temp = tempfile(fileext = '.xlsx') #extension for Excel fie
dataURL <- "https://github.com/lrsulli/Project/raw/master/Data/address_list_5_20_13.xlsx" #link to data
download.file(dataURL, destfile = temp, mode = 'wb') #temporarily download file

data_address = read_excel(temp, sheet = 1) #get data
```

```{r Merge Data: Recodes}
# Prepare recode file
names(data_recode)
data_recode = data_recode[,c(1,5:6,14:15,19:20)] #only keep necessary variables
names(data_recode)[1] <- "STUDYID" #rename to match initial data set

# Merge recode file with initial data set
data = merge(data_initial, data_recode, by="STUDYID")
```

```{r Merge Data: Addresses}
# Prepare address list file
names(data_address)[1] <- "STUDYID" #rename to match initil data set

# Merge address list with initial data set and recodes
data = merge(data, data_address, by="STUDYID")

data = data.frame(data) #convert to data frame
```

```{r Import Data: Census 1}
# Import first of three census data files
temp = tempfile(fileext = '.dta') #extension for Stata data file
dataURL <- "https://github.com/lrsulli/Project/raw/master/Population_Data%204_7_17.dta" #link to data
download.file(dataURL, destfile = temp, mode = 'wb') #temporarily download file

data_census1 = read.dta13(temp) #get data
```

```{r Import Data: Census 2}
# Import second of three census data files
temp = tempfile(fileext = '.dta') #extension for Stata data file
dataURL <- "https://github.com/lrsulli/Project/raw/master/Census_Data%204_28_17.dta" #link to data
download.file(dataURL, destfile = temp, mode = 'wb') #temporarily download file

data_census2 = read.dta13(temp) #get data
```

```{r Import Data: Census 3}
# Import third of three census data files
temp = tempfile(fileext = '.dta') #extension for Stata data file
dataURL<-"https://github.com/lrsulli/Project/raw/master/tract10detroit_povertypop_123mile.dta" #link to data
download.file(dataURL, destfile = temp, mode = 'wb') #temporarily download file

data_census3 = read.dta13(temp) #get data
```

```{r Merge Data: Census}
# Merge first two census data files (Census1 and Census2)
data_census = merge(data_census1, data_census2, by="tr10fips", all=T) #keep all tracts

# Merge third census data file (Census3 with Census1 and Census2)
data_census = merge(data_census, data_census3, by="tr10fips", all=T) #keep all tracts

data_census = data.frame(data_census) #convert to data frame
```

```{r Merge Data: Census with Survey Data}
# Merge Census data and survey data
data = merge(data, data_census, by='STUDYID') #only keep tracts that have organizations

data = data.frame(data) #convert to data frame
```

```{r Check Variable Names}
# Check variable names of data
names(data)
```

```{r Drop Variables}
# Create a copy of original data set
data_copy = data

# Only keep necessary variables
data = data_copy[,c('tr10fips','STUDYID','Q5','Q6_1','Q6_2','Q6_3','Q6_4','Q6_5','Q7','Q8_1','Q8_2','Q8_3','Q8_4','Q8_5','Q8_6','Q8_7','Q8_8','Q9','Q10_1','Q10_2','Q10_3','Q10_4','Q10_5','Q14','Q15_1','Q15_2','Q15_3','Q15_4','Q15_5','Q15_6','Q15_7','Q15_8','Q15_9','Q15_10','Q15_11','Q15_12','Q15_13','Q12RC','Street.Address','City','State','Zip','County','povpop10071','povpopd71','povpop_1m',"povpopd711mile","povpop_3m","povpopd713mile","nhwht71","pop71","nhwht711mile","nhwht713mile","blk71","blk711mile","blk713mile","hsp71","hsp711mile","hsp713mile","hhsnapfam271","hhsnapfam171","hhsnapfam2711mile","hh711mile","hhsnapfam2713mile","hh713mile")]
```

```{r Rename Variables}
# Check variable names of data
names(data)

# Rename identification variables
names(data)[1] <- "tract"
names(data)[2] <- "id"

# Rename types of meal programs
names(data)[3] <- "meals"
names(data)[4] <- "hot_meals"
names(data)[5] <- "home_meals" #Home delivered meals
names(data)[6] <- "community_kitchen"
names(data)[7] <- "child_meals"
names(data)[8] <- "meal_other" #Offer other types of meal programs

# Rename types of grocery programs
names(data)[9] <- "groceries"
names(data)[10] <- "pantry"
names(data)[11] <- "backpack"
names(data)[12] <- "home_groceries" #Home delivered groceries
names(data)[13] <- "mobile_pantry"
names(data)[14] <- "mobile_market"
names(data)[15] <- "supply_other" #Supply food to other programs
names(data)[16] <- "community_garden"
names(data)[17] <- "groceries_other" #Offer other types of grocery programs

# Rename types of food related benefit programs
names(data)[18] <- "food_ben" #Offers food-related benefits
names(data)[19] <- "snap"
names(data)[20] <- "wic"
names(data)[21] <- "school" #School lunch or breakfast
names(data)[22] <- "gift" #Gift card or voucher
names(data)[23] <- "food_ben_other" #Offer other types of food-related benefits

# Rename types of non-food related benefit programs
names(data)[24] <- "nonfood_ben" #Offers non-food related benefits
names(data)[25] <- "job" #Job training or assistance
names(data)[26] <- "house" #Housing assistance
names(data)[27] <- "utility"
names(data)[28] <- "legal"
names(data)[29] <- "educ" #GED or education assistance
names(data)[30] <- "health"
names(data)[31] <- "counseling"
names(data)[32] <- "trans" #Transportation assistance
names(data)[33] <- "cloth" #Clothing or furniture
names(data)[34] <- "ref" #Referrals to other programs
names(data)[35] <- "medicaid" #Medicaid or CHIP
names(data)[36] <- "money" #Financial, tax prep, budgeting
names(data)[37] <- "nonfood_ben_other" #Offer other types of non-food related benefits

# Rename number of clients served per month
names(data)[38] <- "clients"
```

```{r Generate Census Variables}
# Generate poverty rate variables
data <- mutate(data, pov_rateT = povpop10071 / povpopd71) #Rate within tract
data <- mutate(data, pov_rate1 = povpop_1m / povpopd711mile) #Rate within 1 mile
data <- mutate(data, pov_rate3 = povpop_3m / povpopd713mile) #Rate within 3 miles

# Reconicle naming discrepancies between census data sets
# Will use poverty rate within 1 mile for missing within tract poverty rates
data_census$povpop10071[is.na(data_census$povpop10071)] <- 0 #Convert NA's to 0

data_census <- mutate(data_census, pov_rateT = ifelse(povpop10071==0, povpop100711mile / povpopd711mile, povpop10071 / povpopd71)) #Replace missing values with the correct rate

# Generate White demographic variables
data <- mutate(data, white_rateT = nhwht71 / pop71) #Rate within tract
data <- mutate(data, white_rate1 = nhwht711mile / povpopd711mile) #Rate within 1 mile
data <- mutate(data, white_rate3 = nhwht713mile / povpopd713mile) #Rate within 3 miles

# Gnerate Black demographic variables
data <- mutate(data, black_rateT = blk71 / pop71) #Rate within tract
data <- mutate(data, black_rate1 = blk711mile / povpopd711mile) #Rate within 1 mile
data <- mutate(data, black_rate3 = blk713mile / povpopd713mile) #Rate within 3 miles

# Generate Hispanic demographic variables
data <- mutate(data, hisp_rateT = hsp71 / pop71) #Rate within tract
data <- mutate(data, hisp_rate1 = hsp711mile / povpopd711mile) #Rate within 1 mile
data <- mutate(data, hisp_rate3 = hsp713mile / povpopd713mile) #Rate within 3 miles

# Generate SNAP rates
data <- mutate(data, snap_rateT = hhsnapfam271 / hhsnapfam171) #Rate within tract
data <- mutate(data, snap_rate1 = hhsnapfam2711mile / hh711mile) #Rate within 1 mile
data <- mutate(data, snap_rate3 = hhsnapfam2713mile / hh713mile) #Rate within 3 miles
```

```{r Generate County FIPS Variables}
# Need county FIPS variable to focus analysis on Detroit metro area

# Prepare to split census tract identifyer
str(data$tract)
str(data_census$tr10fips)

# Create fips number without state identifier (first two digits)
data <- mutate(data, tract_short = substr(tract, 3, 11))
data_census <- mutate(data_census, tract_short = substr(tr10fips, 3, 11))

# Create county FIPS code variable
data <- mutate(data, county_fips = substr(tract, 3, 5))
data_census <- mutate(data_census, county_fips = substr(tr10fips, 3, 5))
```

### EXPLORING DICHOTOMOUS DATA

#### Meal Programs

```{r Meals: Distribution}
# Distribution of values
pander(table(data$meals), stlye = 'rmarkdown', caption = "Number of food pantries offering meal programs.")
```

```{r}
data_table = data[,c('meals','groceries','food_ben','nonfood_ben')]
```


```{r Meals: Frequencies}
# Relative Frequencies
pander((prop.table(table(data$meals)))*100, stlye = 'rmarkdown', caption = "Percent of food pantries offering meal programs.", digits = 3)

pander(prop.table(table(data_table))*100, stlye = 'rmarkdown', caption = "Percent of food pantries offering meal programs.", digits = 3)
```

```{r Meals: Chi Square}
# Are the difference significant?
pander(chisq.test(table(data$meals)), stlye = 'rmarkdown', caption = "Chi square test for food pantries offering meal programs")
```

```{r Meals: Central Measure}
# Central measurement and dispersion
getMode(data$meals)
```

#### Groceries

```{r Groceries: Distribution}
# Distribution of values
table(data$groceries)
```

```{r Groceries: Frequencies}
# Relative Frequencies
prop.table(table(data$groceries))
```

```{r Groceries: Chi Square}
# Are the difference significant?
distribution = table(data$groceries)
chisq.test(distribution)
```

```{r Groceries: Central Measure}
# Central measurement and dispersion
getMode(data$groceries)
```

#### Food Related Benefits

```{r Food Benefits: Distribution}
# Distribution of values
table(data$food_ben)
```

```{r Food Benefits: Frequencies}
# Relative Frequencies
prop.table(table(data$food_ben))
```

```{r Food Benefits: Chi Square}
# Are the difference significant?
distribution = table(data$food_ben)
chisq.test(distribution)
```

```{r Food Benefits: Central Measure}
# Central measurement and dispersion
getMode(data$food_ben)
```

#### Non-Food Related Benefits

```{r Non-Food Benefits: Distribution}
# Distribution of values
table(data$nonfood_ben)
```

```{r Non-Food Benefits: Frequencies}
# Relative Frequencies
prop.table(table(data$nonfood_ben))
```

```{r Non-Food Benefits: Chi Square}
# Are the difference significant?
distribution = table(data$nonfood_ben)
chisq.test(distribution)
```

```{r Non-Food Benefits: Central Measure}
# Central measurement and dispersion
getMode(data$nonfood_ben)
```

### EXPLORING COUNT VARIABLES

#### Average Number of Clients Served per Month

```{r Clients: Centrality}
# Centrality
summary(data$clients)
```

```{r Clients: Skewness}
# Skewness
skewness(data$clients, na.rm = T)
```

```{r Clients: Kurtosis}
# Kurtosis
kurtosis(data$clients, na.rm = T)
```

```{r Clients: Histogram}
# Histogram
hist(data$clients)
hist(log(data$clients))
```

### Mapping

```{r Map Link}
# Link to map
compressedMap= "https://github.com/lrsulli/Project/raw/master/map/2010_Census_Tracts_v17a.zip"
```

```{r Unzip Map}
# Unzip compressed map folder
temp=tempfile()
download.file(compressedMap, temp)
unzip(temp)
```

```{r Shapefiles}
# Determine which shapefiles are in folder
(maps = list.files(pattern = 'shp'))
```

```{r Select Map}
# Select the map
tractMap <- rgdal::readOGR("2010_Census_Tracts_v17a.shp", stringsAsFactors=F)
```

```{r Explore Map Data}
names(tractMap) #check variable names
str(tractMap$LINK) #check LINK (FIPS code) variable type

# Change LINK (FIPS code) variable into an interger
tractMap$NAME=as.numeric(tractMap$LINK)
```

```{r Select Counties}
# Only need counties where pantries are located (Detroit metro area)

# Keep Wayne, Macomb, Oakland, and Washtenaw Counties (FIPS = 163, 099, 125, and 161)
map_counties = subset(tractMap, CNTY_CODE=='163' | CNTY_CODE=='099' | CNTY_CODE=='125' | CNTY_CODE=='161')

data_counties = data_census[!duplicated(data_census[c('tract_short')]),] #drop duplicate tracts

# Merge map data with census data
map_counties = merge(map_counties, data_counties, by.x='LINK', by.y='tract_short', all.x=F)
```

```{r Check County Map}
# Check map to determine if correct counties selected
plot(map_counties, col='black')
```

```{r Geocoding, eval=FALSE}
# Only ran once because it takes awhile, wrote into an .csv file and put in Github repo

# Prepare data_address data frame
data_address$address <- do.call(paste, c(data_address[c("Street Address", "City", "State")], sep = ",")) #correct single line address format

# Got code from https://qanda.science/r/3956223_batch-geocoding-with-googleway-r-how-to.jsp

# API key for Google geocoding
api_key = "AIzaSyC2uRbBeIFBwdSiH6KH69Stx_TUoqPN0bY"

# Geocode addresses (only do once because of time)
res <- apply(data_address, 1, function(x){
  google_geocode(address = x[['address']],
                 key = api_key)
})

# Add geocode results to data_address data frame
data_address$location <- lapply(res, function(x){
  x$results$geometry$location
})

# Create latitude and longitude variables from results
data_address$location = as.character(data_address$location) #destring location variable

data_address <- mutate(data_address, lat = substr(location, 12, 20)) #get latitude numbers
data_address <- mutate(data_address, lon = substr(location, 29, 38)) #get longitude numbers

# Merge latitude and longitude with main data set to get Study ID's
map_address <- merge(data_address, data, by.x='STUDYID', by.y='id')

# Keep only necessary variables
map_address = map_address[,c('STUDYID','lat','lon')]

# Create .csv file with geocode results
write.csv(map_address, "geocoded_addresses.csv") #saved to Github repo
```

```{r Import Data: Geocoded Addresses}
temp = tempfile(fileext = '.csv') #extension for Excel file
dataURL <- "https://raw.githubusercontent.com/lrsulli/Project/master/geocoded_addresses.csv" #link to data
download.file(dataURL, destfile = temp, mode = 'wb') #temporarily download file

map_address = read.csv(temp, header = TRUE, sep = ",") #get data

# Redefine latitude and longitude variables
map_address$lat = as.character(map_address$lat)
map_address$lon = as.character(map_address$lon) 
```

```{r Select Variable}
# Want to plot within tract poverty rate
varToPLot=map_counties$pov_rateT
```

```{r Plot Characteristics}
# Number of intervals
numberOfClasses = 5 

# Color pallete
colorForScale='YlGnBu'
colors = brewer.pal(numberOfClasses, colorForScale)

intervals <- classIntervals(varToPLot, numberOfClasses, 
                            style = "quantile",
                            dataPrecision=2)
colorPallette <- findColours(intervals, colors)
```

```{r Plot}
#Plot characteristics
legendText="Poverty Rate" #legend title
shrinkLegend=0.8 #legend size
title="Poverty Rate by Census Tract"
shrinkPoints=0.35 #point size

plot(map_counties, col = 'grey') #plot background map (tracts without pantries)
plot(map_counties, col = colorPallette, main=title,border='black',add=T) #plot poverty rates

legend('topright', legend = names(attr(colorPallette, "table")), 
       fill = attr(colorPallette, "palette"), cex = shrinkLegend, 
       bty = "n",
       title=legendText)

points(map_address$lon, map_address$lat, col = "red", pch =19, cex = shrinkPoints) #add pantry locations
```
